FIRST_PRODUCT_NUMBER = FIRST_ACCOUNT_NUMBER = 0
SECOND_PRODUCT_NUMBER = 100
THIRD_PRODUCT_NUMBER = 200
FOURTH_PRODUCT_NUMBER = 500
FIFTH_PRODUCT_NUMBER = 1000
FIRST_CRAWL_NUMBER = SECOND_ACCOUNT_NUMBER = 1
SECOND_CRAWL_NUMBER = THIRD_ACCOUNT_NUMBER = 2
THIRD_CRAWL_NUMBER = 4
FOURTH_CRAWL_NUMBER = 8
FIFTH_CRAWL_NUMBER = 30
FOURTH_ACCOUNT_NUMBER = 5
FIFTH_ACCOUNT_NUMBER = 10
